services:
  db:
    image: postgres
    container_name: postgres-devdojo
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - devdojo_data:/var/lib/postgres

volumes:
  devdojo_data:
